# example configuration file for yousable

paths:
  meta: /mnt/persist/cache/yousable/meta
  out: /mnt/persist/cache/yousable/out
  tmp: /mnt/persist/cache/yousable/tmp
  live: /mnt/persist/cache/yousable/live
  x_accel: /out

secrets:
  user1: pbkdf2:sha256:260000$T0zVMOiEkdPU3FtD$30994c8b02a3e818636c3148594ba61aa8fe2086dca6e3c16ced92fb74d166e7
  # ^ `pass1` hashed, use `yousable hash` to generate one

feed_defaults:
  load_entries: 5              # query only the last L videos from youtube
  keep_entries: 10             # keep at least the last K videos on disk
  keep_entries_seconds: 86400  # keep videos that are less than M seconds old
  live_slice_seconds: 1200     # fill paths.live with fragments N seconds long
  poll_seconds: 1200           # look for new videos roughly P seconds often
  profiles: [ default ]

feeds:
  AdaDeranaNews:  # random channel with frequent updates, sometimes livestreams
    url: https://www.youtube.com/c/AdaDeranaNews  # /c/ url
    extra_urls: [ https://www.youtube.com/c/AdaDeranaNews/live ]
    poll_seconds: 600

# BlenderStudio:  # slowly updating channel, has subtitles
#   url: https://youtube.com/channel/UCz75RVbH8q2jdBJ4SnwuZZQ  # /channel/ url
#   profiles: [ default, small ]

# HS:  # used as long livestream example in testing
#   load_entries: 1
#   keep_entries: 10
#   url: https://www.youtube.com/c/Hearthstone
#   extra_urls: [ https://www.youtube.com/c/Hearthstone/live ]
#   profiles: [ small, audio ]

# JG:  # has mostly streams
#   load_entries: 2
#   url: https://www.youtube.com/channel/UCWAIvx2yYLK_xTYD4F2mUNw
#   extra_urls:
#     - https://www.youtube.com/channel/UCWAIvx2yYLK_xTYD4F2mUNw/live
#     - https://www.youtube.com/playlist?list=UUWAIvx2yYLK_xTYD4F2mUNw
#   profiles: [ small, audio ]
#   overrides:
#     title: Живой Гвоздь  # change feed title

# Kurzgesagt:  # sponsorblock example
#   url: https://www.youtube.com/user/Kurzgesagt  # /user/ url
#   load_entries: 1
#   # cut out sponsor segments reported to Sponsorblock
#   sponsorblock_remove: [ sponsor ]
#   profiles: [ default, small ]

profiles:
  default:
    container: mkv
    download:
      format_sort: [ 'res:720' ]  # 720p, see yt-dlp README for description
    live:
      video:
        format_sort: [ 'res:720', 'ext:mp4' ]   # or video streaming stalls
  small:
    container: mkv
    download:
      format_sort: [ 'res:480' ]
    live:
      video:
        format_sort: [ 'res:480', 'ext:mp4' ]
  audio:
    video: false
    container: opus
    download:
      format: 'ba[vcodec=none]'
      format_sort: [ 'acodec:opus' ]
    live:
      audio:
        format_sort: [ 'acodec:opus' ]
